kind: Namespace
apiVersion: v1
metadata:
  name: prod
---
kind: Service
apiVersion: v1
metadata:
  name: dev-ops-test
  namespace: prod
spec:
  selector:
    app: dev-ops-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dev-ops-test
  namespace: prod
  labels:
    app: dev-ops-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev-ops-test
  template:
    metadata:
      labels:
        app: dev-ops-test
    spec:
      containers:
        - name: dev-ops-test
          image: asia.gcr.io/kube-test-222309/dev-ops-test@sha256:309e1a11998a922a4b5465d59f94ad7e75f244f2
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
